### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by ardeshir** [msfidelis/serverless-architecture-boilerplate-go#1]
$ make build
dep ensure
dep: WARNING: Unknown field in manifest: prune
env GOOS=linux go build -ldflags="-s -w" -o bin/books/endpoints/create modules/books/endpoints/create.go
modules/books/endpoints/create.go:14:2: cannot find package "serverless-architecture-boilerplate-go/pkg/libs/dynamoclient" in any of:
	/Users/administrator/gocode/src/github.com/msfidelis/serverless-architecture-boilerplate-go/vendor/serverless-architecture-boilerplate-go/pkg/libs/dynamoclient (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/serverless-architecture-boilerplate-go/pkg/libs/dynamoclient (from $GOROOT)
	/Users/administrator/gocode/src/serverless-architecture-boilerplate-go/pkg/libs/dynamoclient (from $GOPATH)
modules/books/endpoints/create.go:15:2: cannot find package "serverless-architecture-boilerplate-go/pkg/libs/sqsclient" in any of:
	/Users/administrator/gocode/src/github.com/msfidelis/serverless-architecture-boilerplate-go/vendor/serverless-architecture-boilerplate-go/pkg/libs/sqsclient (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/serverless-architecture-boilerplate-go/pkg/libs/sqsclient (from $GOROOT)
	/Users/administrator/gocode/src/serverless-architecture-boilerplate-go/pkg/libs/sqsclient (from $GOPATH)
modules/books/endpoints/create.go:16:2: cannot find package "serverless-architecture-boilerplate-go/pkg/models/book" in any of:
	/Users/administrator/gocode/src/github.com/msfidelis/serverless-architecture-boilerplate-go/vendor/serverless-architecture-boilerplate-go/pkg/models/book (vendor tree)
	/usr/local/Cellar/go/1.12.1/libexec/src/serverless-architecture-boilerplate-go/pkg/models/book (from $GOROOT)
	/Users/administrator/gocode/src/serverless-architecture-boilerplate-go/pkg/models/book (from $GOPATH)
make: *** [build] Error 1

**Comment by ardeshir** [comment]
Fixed:  export GO111MODULE="on"

**Comment by msfidelis** [comment]
Hello @ardeshir ! Thanks for your report! I fixed it on Makefile to prevent this issue. 
https://github.com/msfidelis/serverless-architecture-boilerplate-go/pull/2
